[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11.4"
noto-sans-mono-bitmap = "0.2.0"
once_cell = { version = "1.18.0", default-features = false }
spin = "0.9.8"
